### ISSUE TITLE
Query1

### ISSUE THREAD

**Issue by jagalitiger** [bipinkrish/Mdisk-Downloader-Bot#11] opened 2022-08-28 15:34 UTC
Bro Stream output come without default thumb... Any possibility to come with default video thumb. Or difficulty to add

**Comment by aakash2021-cap** [comment] 2022-08-28 16:27
> Bro Stream output come without default thumb... Any possibility to come with default video thumb. Or difficulty to add

NO BRO IT'S WORKING FINE✅

**Comment by AsuranJ** [comment] 2022-08-28 16:31
![Uploading IMG_20220828_220112.jpg…]()
Chk this

**Comment by AsuranJ** [comment] 2022-08-28 17:40
![IMG_20220828_220112](https://user-images.githubusercontent.com/71362075/187087425-f1235915-4c36-402c-bca9-bfb4805758da.jpg)

**Comment by aakash2021-cap** [comment] 2022-08-28 17:42
> ![IMG_20220828_220112](https://user-images.githubusercontent.com/71362075/187087425-f1235915-4c36-402c-bca9-bfb4805758da.jpg)

![Screenshot_2022-08-28-23-11-48-667_org telegram messenger](https://user-images.githubusercontent.com/84575647/187087510-e5eefd51-c9cd-4781-b8e7-374aad964e92.jpg)

**Comment by aakash2021-cap** [comment] 2022-08-28 17:43
> ![IMG_20220828_220112](https://user-images.githubusercontent.com/71362075/187087425-f1235915-4c36-402c-bca9-bfb4805758da.jpg)



working bro see above pic

**Comment by AsuranJ** [comment] 2022-08-28 17:45
I am told that video default thumnail.. Not black screen bro

**Comment by AsuranJ** [comment] 2022-08-28 17:46
![IMG_20220828_231550](https://user-images.githubusercontent.com/71362075/187087659-d19b144d-ef89-487d-abe0-d1ce263db9ce.jpg)
Check this video this is a default thumb of this video

**Comment by aakash2021-cap** [comment] 2022-08-28 17:46
> I am told that video default thumnail.. Not black screen bro

Bro i also change doc to video mode and set thumb and put link it's work well but one error is we can't use show thumb

**Comment by aakash2021-cap** [comment] 2022-08-28 17:47
> ![IMG_20220828_231550](https://user-images.githubusercontent.com/71362075/187087659-d19b144d-ef89-487d-abe0-d1ce263db9ce.jpg) Check this video this is a default thumb of this video

M okay bro i understood

**Comment by AsuranJ** [comment] 2022-08-28 17:48
S... Manual thumb always wrk fine.. Need default every time i rename that video

**Comment by aakash2021-cap** [comment] 2022-08-28 17:52
> S... Manual thumb always wrk fine.. Need default every time i rename that video

But /show not show the default thumb

**Comment by bipinkrish** [comment] 2022-08-28 18:15
I get what you are saying, i will check on that

**Comment by AsuranJ** [comment] 2022-08-28 18:16
Tq

**Comment by bipinkrish** [comment] 2022-08-28 18:22
> > S... Manual thumb always wrk fine.. Need default every time i rename that video
> 
> But /show not show the default thumb

Not working? Did you get "Thumbnail not set" message or nothing?

**Comment by aakash2021-cap** [comment] 2022-08-29 01:36
> > > S... Manual thumb always wrk fine.. Need default every time i rename that video
> > 
> > 
> > But /show not show the default thumb
> 
> Not working? Did you get "Thumbnail not set" message or nothing?

If thumbnail is not set. It give the message thumb not set ,after i set the thumb and use show command to see default thumb it won't work and show this error

📌pyrogram.errors.exceptions.bad_request_400.InputRequestTooLong: Telegram says: [400 INPUT_REQUEST_TOO_LONG] - The input request is too long (caused by "messages.SendMedia"

**Comment by bipinkrish** [comment] 2022-08-29 02:55
> > > > S... Manual thumb always wrk fine.. Need default every time i rename that video
> > > 
> > > 
> > > But /show not show the default thumb
> > 
> > 
> > Not working? Did you get "Thumbnail not set" message or nothing?
> 
> If thumbnail is not set. It give the message thumb not set ,after i set the thumb and use show command to see default thumb it won't work and show this error
> 
> 📌pyrogram.errors.exceptions.bad_request_400.InputRequestTooLong: Telegram says: [400 INPUT_REQUEST_TOO_LONG] - The input request is too long (caused by "messages.SendMedia"

Try giving small filename for image because it's working normally

**Comment by aakash2021-cap** [comment] 2022-08-29 03:11
> > > > > S... Manual thumb always wrk fine.. Need default every time i rename that video
> > > > 
> > > > 
> > > > But /show not show the default thumb
> > > 
> > > 
> > > Not working? Did you get "Thumbnail not set" message or nothing?
> > 
> > 
> > If thumbnail is not set. It give the message thumb not set ,after i set the thumb and use show command to see default thumb it won't work and show this error
> > 📌pyrogram.errors.exceptions.bad_request_400.InputRequestTooLong: Telegram says: [400 INPUT_REQUEST_TOO_LONG] - The input request is too long (caused by "messages.SendMedia"
> 
> Try giving small filename for image because it's working normally

Not working bro
👇
![Screenshot_2022-08-29-08-40-58-562_org telegram messenger](https://user-images.githubusercontent.com/84575647/187115595-20f11349-8991-49f5-a968-081b466cb8db.jpg)

**Comment by aakash2021-cap** [comment] 2022-08-29 03:33
Okay bro please update

**Comment by bipinkrish** [comment] 2022-08-29 05:29
this issue is fixed now

**Closed by bipinkrish** 2022-08-29 05:29 UTC
Labels: bug
